name: ProdCI
on:
  push:
    tags:
      - '*[0123456789]'
jobs:
  main:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: reg.b7cloud.com
          username: ${{ secrets.REG_ACCOUNT }}
          password: ${{ secrets.REG_PWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: reg.b7cloud.com/${{ github.repository }}:latest
          build-args: |
            buildEnv=prod
